
export const CNC_HEADER = `
;----------------------------------------
; Generated by Smart CNC Assistant
; Controller: Generic ISO Standard
;----------------------------------------
G17 G90 G54 G71
G64 P0.01
COMPON
SOFT
`;

export const CNC_FOOTER = `
M30
;----------------------------------------
; End of Program
;----------------------------------------
`;