
import { CNCOutput, MachineOperationType, OperationParams, StockDimensions, ToolType, SafetyAuditResult } from "../types";

const fmt = (n: number | undefined | null) => {
  if (n === undefined || n === null || isNaN(n)) return "0";
  // Keep 3 decimal places for metric precision
  return parseFloat(n.toFixed(3)).toString();
};

const getToolName = (type: ToolType, diameter: number): string => {
  // Tool naming convention.
  switch (type) {
    case ToolType.DRILL: return `DRILL_${diameter}`;
    case ToolType.FACE_MILL: return `FACEMILL_${diameter}`;
    case ToolType.BALL_MILL: return `BALL_${diameter}`;
    case ToolType.END_MILL: 
    default: 
        return `CUTTER_${diameter}`;
  }
};

export const generateCNCCode = (
  stock: StockDimensions,
  operations: OperationParams[],
  explanation: string
): CNCOutput => {
  let mainBlocks: string[] = [];
  let subBlocks: string[] = []; 
  
  // 1. Program Header
  const programName = "AI_CAM_PROG";
  mainBlocks.push(`%_N_${programName}_MPF`);
  mainBlocks.push(`;$PATH=/_N_WKS_DIR/_N_SHOPMILL_WPD`);
  mainBlocks.push(`; Generated by Intelligent CNC Assistant`);
  mainBlocks.push(`; Date: ${new Date().toLocaleDateString()}`);
  mainBlocks.push(``);
  
  // 2. Initial Settings
  mainBlocks.push(`G17 G90 G54 G71`); // XY Plane, Abs coords, Offset 1, Metric
  mainBlocks.push(`G64 P0.01`);      // Continuous path mode with smoothing
  mainBlocks.push(`COMPON`);         // Compressor on
  mainBlocks.push(`SOFT`);           // Soft acceleration
  mainBlocks.push(``);

  // 3. Workpiece Definition
  const zAbs = -Math.abs(stock.height); 
  
  if (stock.shape === 'CYLINDRICAL') {
    // Cylinder centered at X0 Y0
    mainBlocks.push(`WORKPIECE(,"",,"CYLINDER",0,0,${fmt(zAbs)},0,${fmt(stock.diameter)})`);
  } else {
    // Rectangle centered at X0 Y0
    mainBlocks.push(`WORKPIECE(,"",,"RECTANGLE",0,0,${fmt(zAbs)},0,${fmt(stock.length)},${fmt(stock.width)})`);
  }
  mainBlocks.push(``);

  // 4. Operations
  let currentToolName = "";

  operations.forEach((op, index) => {
    if (op.type === MachineOperationType.GENERAL_CHAT) {
        mainBlocks.push(`; ------------------------------------`);
        mainBlocks.push(`; NOTE: General Chat / Explanation Only`);
        mainBlocks.push(`; No machining operations generated for this step.`);
        mainBlocks.push(`; ------------------------------------`);
        mainBlocks.push(``);
        return;
    }

    const contourName = `CONT_${index + 1}`; 
    const startLabel = `LAB_S_${contourName}`;
    const endLabel = `LAB_E_${contourName}`;

    mainBlocks.push(`; ------------------------------------`);
    mainBlocks.push(`; OP ${index + 1}: ${op.type} (Z_Start=${op.z_start}, Depth=${op.z_depth})`);

    // Tool Change
    const toolName = getToolName(op.tool_type, op.tool_diameter);
    if (toolName !== currentToolName) {
        if (currentToolName !== "") {
            mainBlocks.push(`M5`);
            mainBlocks.push(`M9`);
            mainBlocks.push(`M1`); // Optional stop
        }
        mainBlocks.push(`T="${toolName}"`);
        mainBlocks.push(`M6`);
        const S = op.spindle_speed || 3000;
        const F = op.feed_rate || 800;
        mainBlocks.push(`S${S} M3 M8`);
        mainBlocks.push(`F${F}`);
        mainBlocks.push(`D1`); // Tool offset 1
        currentToolName = toolName;
    }

    // Safety height move
    mainBlocks.push(`G0 Z50`); 
    mainBlocks.push(`G0 X${fmt(op.x)} Y${fmt(op.y)}`); // Pre-position
    
    // Move to calculated start Z + safety
    mainBlocks.push(`G0 Z${fmt(op.z_start + 5)}`);  

    switch (op.type) {
        case MachineOperationType.FACE_MILL:
            mainBlocks.push(`; FACE MILLING`);
            const fmW = op.width || 100;
            const fmL = op.length || 100;
            const fmX = op.x - fmW/2;
            const fmY = op.y - fmL/2;
            // CYCLE61 params: (Retract, RefPlane, SafetyDist, Depth, P1, P2, L1, L2, ...)
            mainBlocks.push(`CYCLE61(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, ${fmt(fmX)}, ${fmt(fmY)}, ${fmt(fmW)}, ${fmt(fmL)}, 1, 1, ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, 11, 0, 1, 1)`);
            break;

        case MachineOperationType.CIRCULAR_POCKET:
            mainBlocks.push(`; CIRCULAR POCKET`);
            // CYCLE77: (Retract, RefPlane, SafetyDist, Depth, Abs/Inc, Diameter, ...)
            mainBlocks.push(`CYCLE77(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, 0, ${fmt(op.diameter! / 2)}, ${fmt(op.x)}, ${fmt(op.y)}, ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, ${fmt(op.feed_rate)}, 0, 0, 0, 1, )`);
            break;

        case MachineOperationType.RECTANGULAR_POCKET:
            mainBlocks.push(`; RECTANGULAR POCKET`);
            // POCKET3: (Retract, RefPlane, SafetyDist, Depth, Abs/Inc, Len, Wid, Angle, ...)
            mainBlocks.push(`POCKET3(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, 0, ${fmt(op.length)}, ${fmt(op.width)}, 0, ${fmt(op.x)}, ${fmt(op.y)}, 0, ${fmt(op.feed_rate)}, ${fmt(op.feed_rate)}, ${fmt(op.step_down)}, 2, 0, 0, , , )`);
            break;

        case MachineOperationType.BOSS_MILLING:
            mainBlocks.push(`; BOSS / SPIGOT MILLING`);
            
            // Check if we have an arbitrary contour defined by path_segments
            if (op.path_segments && op.path_segments.length > 0) {
                 mainBlocks.push(`; CONTOUR SPIGOT (CYCLE72)`);
                 // Define Contour
                 mainBlocks.push(`CYCLE62("${contourName}", 1, , )`);
                 // Call Contour Milling (CYCLE72 for Path Milling)
                 mainBlocks.push(`CYCLE72("${contourName}", 5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, , , , , ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, 1, 21, 2, 1, 0, 1, 2, )`);
                 
                 // Generate Subroutine for the shape
                 subBlocks.push(``);
                 subBlocks.push(`; Contour Definition: ${contourName}`);
                 subBlocks.push(`${startLabel}:`);
                 subBlocks.push(`G17 G90 DIAMOF`);
                 
                 // Use path_segments[0] as start point for BOSS
                 let currentX = op.path_segments[0].x;
                 let currentY = op.path_segments[0].y;
                 subBlocks.push(`G0 X${fmt(currentX)} Y${fmt(currentY)}`);
                 
                 op.path_segments.slice(1).forEach(seg => {
                     if (seg.type === 'LINE') {
                         subBlocks.push(`G1 X${fmt(seg.x)} Y${fmt(seg.y)}`);
                     } else if (seg.type === 'ARC_CW') {
                         const i = (seg.cx || 0) - currentX; 
                         const j = (seg.cy || 0) - currentY;
                         subBlocks.push(`G2 X${fmt(seg.x)} Y${fmt(seg.y)} I${fmt(i)} J${fmt(j)}`);
                     } else if (seg.type === 'ARC_CCW') {
                         const i = (seg.cx || 0) - currentX; 
                         const j = (seg.cy || 0) - currentY;
                         subBlocks.push(`G3 X${fmt(seg.x)} Y${fmt(seg.y)} I${fmt(i)} J${fmt(j)}`);
                     }
                     currentX = seg.x;
                     currentY = seg.y;
                 });
                 
                 // Close loop back to start for boss
                 subBlocks.push(`G1 X${fmt(op.path_segments[0].x)} Y${fmt(op.path_segments[0].y)}`);

                 subBlocks.push(`${endLabel}:`);
                 subBlocks.push(`RET`);
                 
            } else if (op.boss_shape === 'CYLINDRICAL' || (op.diameter && !op.width)) {
                 mainBlocks.push(`; CIRCULAR SPIGOT (CYCLE77)`);
                 // Params: Retract, RefPlane, Safety, Depth, Abs, Dia, CenterX, CenterY, MaxDepth...
                 mainBlocks.push(`CYCLE77(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, 0, ${fmt(op.diameter)}, ${fmt(op.x)}, ${fmt(op.y)}, ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, ${fmt(op.feed_rate)}, 0, 0, 0, 2, )`);
            } else {
                 mainBlocks.push(`; RECTANGULAR SPIGOT (CYCLE76)`);
                 // Params: Retract, RefPlane, Safety, Depth, Abs, Len, Wid, CenterX, CenterY...
                 mainBlocks.push(`CYCLE76(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, 0, ${fmt(op.length)}, ${fmt(op.width)}, ${fmt(op.corner_radius || 0)}, ${fmt(op.x)}, ${fmt(op.y)}, 0, ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, ${fmt(op.feed_rate)}, 0, 0, 0, 2, )`);
            }
            break;

        case MachineOperationType.DRILL:
            mainBlocks.push(`; DRILLING`);
            mainBlocks.push(`MCALL CYCLE81(5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, 0)`);
            mainBlocks.push(`HOLES1(${fmt(op.x)}, ${fmt(op.y)}, 0, 0, 0, 1)`);
            mainBlocks.push(`MCALL`);
            break;

        case MachineOperationType.CONTOUR:
            mainBlocks.push(`; CONTOUR MACHINING`);
            mainBlocks.push(`CYCLE62("${contourName}", 1, , )`);
            // Use CYCLE72 for Path Milling (Standard Profiling)
            mainBlocks.push(`CYCLE72("${contourName}", 5, ${fmt(op.z_start)}, 2, -${fmt(op.z_depth)}, , , , , ${fmt(op.step_down)}, ${fmt(op.feed_rate)}, 1, 1, 2, 1, 0, 1, 2, )`);
            
            subBlocks.push(``);
            subBlocks.push(`; Contour Definition: ${contourName}`);
            subBlocks.push(`${startLabel}:`);
            subBlocks.push(`G17 G90 DIAMOF`);
            
            // CONTOUR uses op.x/y as Start Point
            let cX = op.x;
            let cY = op.y;
            subBlocks.push(`G0 X${fmt(cX)} Y${fmt(cY)}`);
            
            if (op.path_segments && op.path_segments.length > 0) {
                 op.path_segments.forEach(seg => {
                     if (seg.type === 'LINE') {
                         subBlocks.push(`G1 X${fmt(seg.x)} Y${fmt(seg.y)}`);
                     } else if (seg.type === 'ARC_CW') {
                         const i = (seg.cx || 0) - cX; 
                         const j = (seg.cy || 0) - cY;
                         subBlocks.push(`G2 X${fmt(seg.x)} Y${fmt(seg.y)} I${fmt(i)} J${fmt(j)}`);
                     } else if (seg.type === 'ARC_CCW') {
                         const i = (seg.cx || 0) - cX; 
                         const j = (seg.cy || 0) - cY;
                         subBlocks.push(`G3 X${fmt(seg.x)} Y${fmt(seg.y)} I${fmt(i)} J${fmt(j)}`);
                     }
                     cX = seg.x;
                     cY = seg.y;
                 });
            } else {
                 // Fallback box path
                 const hw = (op.width || 20) / 2;
                 const hl = (op.length || 20) / 2;
                 subBlocks.push(`G1 X${fmt(op.x + hw)} Y${fmt(op.y)}`);
                 subBlocks.push(`G1 X${fmt(op.x + hw)} Y${fmt(op.y + hl)}`);
                 subBlocks.push(`G1 X${fmt(op.x - hw)} Y${fmt(op.y + hl)}`);
                 subBlocks.push(`G1 X${fmt(op.x - hw)} Y${fmt(op.y - hl)}`);
                 subBlocks.push(`G1 X${fmt(op.x + hw)} Y${fmt(op.y - hl)}`);
                 subBlocks.push(`G1 X${fmt(op.x + hw)} Y${fmt(op.y)}`);
            }

            subBlocks.push(`${endLabel}:`);
            subBlocks.push(`RET`);
            break;
    }
    
    // Retract
    mainBlocks.push(`G0 Z50`);
    mainBlocks.push(``);
  });

  // Footer
  mainBlocks.push(`M30`);
  mainBlocks.push(`; End of Program`);

  return {
    gcode: mainBlocks.join('\n') + (subBlocks.length > 0 ? '\n\n; Subroutines\n' + subBlocks.join('\n') : ''),
    explanation: explanation || "Generated by AI",
    operations: operations,
    stock: stock
  };
};

export const auditGCode = (gcode: string): SafetyAuditResult => {
  const issues: SafetyAuditResult['issues'] = [];
  const lines = gcode.split('\n');
  
  let isSpindleOn = false;
  let isRapid = false;
  let hasFeedRate = false;
  let lineNum = 0;
  
  // Regex helpers
  const getVal = (line: string, char: string) => {
      const regex = new RegExp(`${char}([-+]?[0-9]*\\.?[0-9]+)`);
      const match = line.match(regex);
      return match ? parseFloat(match[1]) : null;
  };

  for (const line of lines) {
      lineNum++;
      const l = line.trim().toUpperCase();
      if (!l || l.startsWith(';') || l.startsWith('//') || l.startsWith('(')) continue;

      // Spindle State
      if (l.includes('M3') || l.includes('M03') || l.includes('M4') || l.includes('M04')) isSpindleOn = true;
      if (l.includes('M5') || l.includes('M05')) isSpindleOn = false;

      // Feed Rate
      if (l.includes('F')) hasFeedRate = true;

      // Motion Mode
      if (l.includes('G0') || l.includes('G00')) isRapid = true;
      else if (l.includes('G1') || l.includes('G01') || l.includes('G2') || l.includes('G02') || l.includes('G3') || l.includes('G03')) isRapid = false;

      // 1. Critical: Rapid into Material
      if (isRapid) {
          const z = getVal(l, 'Z');
          if (z !== null && z < 0) {
              issues.push({
                  severity: 'critical',
                  line: lineNum,
                  message: `检测到 Z 轴快速移动 (G0) 至负值 Z${z}`,
                  suggestion: "存在撞刀风险！请改为 G1 或检查安全高度。"
              });
          }
      }

      // 2. Critical: Cutting without Spindle
      // Assume coordinates X/Y/Z imply a move.
      if (!isRapid && (l.includes('X') || l.includes('Y') || l.includes('Z'))) {
           if (!isSpindleOn) {
               // Only flag if it looks like a cut
               issues.push({
                   severity: 'critical',
                   line: lineNum,
                   message: "切削移动时主轴未启动",
                   suggestion: "在切削前添加 M3 S..."
               });
           }
           
           if (!hasFeedRate) {
               issues.push({
                   severity: 'warning',
                   line: lineNum,
                   message: "未设置进给率 (F)",
                   suggestion: "请设置 F 值 (如 F1000)"
               });
           }
      }
      
      // 3. Info: Missing M30
      // handled implicitly by score check later or just logic here
  }
  
  if (!gcode.includes('M30') && !gcode.includes('M02')) {
      issues.push({
          severity: 'warning',
          message: "程序末尾未发现结束指令 (M30)",
          suggestion: "添加 M30 以结束程序"
      });
  }

  // Calculate Score
  let score = 100;
  const criticals = issues.filter(i => i.severity === 'critical').length;
  const warnings = issues.filter(i => i.severity === 'warning').length;
  
  score -= (criticals * 40);
  score -= (warnings * 10);
  if (score < 0) score = 0;

  return {
      passed: criticals === 0 && score >= 60,
      score,
      issues
  };
};
